CREATE SCHEMA IF NOT EXISTS familybenefit;

GRANT USAGE ON SCHEMA familybenefit TO familyben;
GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA familybenefit TO familyben;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA familybenefit TO familyben;
